version: '3.5'

services:
  urlShorter_db:
    container_name: urlShorter_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=urlShorter
    image: postgres:15.3-alpine

  app:
    build: ./
    container_name: urlShorter_app
    ports:
      - "8080:8080"